# basic site settings
title = "egin"
baseURL = "https://egin.uk/"

# language settings
languageCode = "en-us"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

# disabling taxonomy generator
disableKinds = ["taxonomy", "term"]

# data settings
enableRobotsTXT = true
metaDataFormat = "yaml"
enableGitInfo = true
rssLimit = 10
summarylength = 15
paginate = 6

# sitemap output
[sitemap]
filename = "sitemap.xml"

# custom params
[params]
cloudinaryPrefix = "https://res.cloudinary.com/project-name/image/upload"
googleAnalyticsId = ""

[languages.cy]
    contentDir = "content/cy"
    languageName = "Cymraeg"
    weight = 1
    [languages.cy.params]
        locale = "cy_CY"
[languages.en]
    contentDir = "content/en"
    languageName = "English"
    weight = 2
    [languages.en.params]
        locale = "en_US"